/* AUTO-GENERATED by create_wireframe_sheet.py */
var WF_CONFIG = {
  spreadsheetId: "1oJuLXlho8rlvQz2fqcV8f5IXoH22-HORdAEv94nHX58",
  spreadsheetUrl: "https://docs.google.com/spreadsheets/d/1oJuLXlho8rlvQz2fqcV8f5IXoH22-HORdAEv94nHX58/edit",
  gasUrl: "https://script.google.com/macros/s/AKfycbzmv20ReAmbDzFsvRKcT67prmDAbhCv1TnOs6CBQAQjJya3Ph6-8pX8LmtvShCsPPjJ/exec",
  pages: [
    {
        "id": "blog-detail",
        "sheet": "blog-detail"
    },
    {
        "id": "blog",
        "sheet": "blog"
    },
    {
        "id": "company",
        "sheet": "company"
    },
    {
        "id": "contact",
        "sheet": "contact"
    },
    {
        "id": "delivery-detail",
        "sheet": "delivery-detail"
    },
    {
        "id": "delivery",
        "sheet": "delivery"
    },
    {
        "id": "entry-2027-career",
        "sheet": "entry-2027-career"
    },
    {
        "id": "entry-2027-graduate",
        "sheet": "entry-2027-graduate"
    },
    {
        "id": "entry-2027",
        "sheet": "entry-2027"
    },
    {
        "id": "history",
        "sheet": "history"
    },
    {
        "id": "index",
        "sheet": "index"
    },
    {
        "id": "news-detail",
        "sheet": "news-detail"
    },
    {
        "id": "news",
        "sheet": "news"
    },
    {
        "id": "privacy",
        "sheet": "privacy"
    },
    {
        "id": "products-agricultural",
        "sheet": "products-agricultural"
    },
    {
        "id": "products-industry",
        "sheet": "products-industry"
    },
    {
        "id": "products-other",
        "sheet": "products-other"
    },
    {
        "id": "products-weighing",
        "sheet": "products-weighing"
    },
    {
        "id": "products",
        "sheet": "products"
    },
    {
        "id": "recruit-entry",
        "sheet": "recruit-entry"
    },
    {
        "id": "recruit-faq",
        "sheet": "recruit-faq"
    },
    {
        "id": "recruit-interview-detail",
        "sheet": "recruit-interview-detail"
    },
    {
        "id": "recruit-interview",
        "sheet": "recruit-interview"
    },
    {
        "id": "recruit",
        "sheet": "recruit"
    },
    {
        "id": "service",
        "sheet": "service"
    },
    {
        "id": "top",
        "sheet": "top"
    }
]
};
